### PR TITLE
Nz/model/user series

### LINKED ISSUE #28: user_episodes table
20200829191200-create_user_episodes_table.sql had user_series as its table name. I changed that to user_episodes assuming there was a mistake there. 

I need help on Line 8
`series_id INTEGER NOT NULL REFERENCES user_series(imdb_id) ON DELETE CASCADE`
Could you please confirm is this is correct or does it need to be changed to user_episodes?

Thank you

### PR DESCRIPTION
**Pull request by nisozakuto**

### CODE REVIEW

**Review by Schlaffmatthewj — COMMENTED** [review]
Idk about changing the table names? I thought you were strictly talking about the variable after you map.. why change the name of the database table?

**Comment by nisozakuto** [comment]
which one table_series or table episodes?

**Comment by Schlaffmatthewj** [comment]
Both of them? Why are we changing the tables?

**Comment by nisozakuto** [comment]
This one had an error: 
https://github.com/lsysophia/MSN-MTDB/pull/29/commits/a8e9f4bb26bdba7ecaed25c53b0093b028d8a1b4

Table_series, I changed it to show, for the consistency, I can change it back

**Review by lsysophia — APPROVED** [review]

**Review by Schlaffmatthewj — APPROVED** [review]

**Pull request merged**
